= Running Commodore

Commodore is written in Python and it requires external dependencies.
We provide Commodore as a container image and a Python package on PyPI.

[NOTE]
====
For local development, the procedure is documented in the https://github.com/projectsyn/commodore/blob/master/README.md[README].
====

Commodore interacts with Git repositories that might require authorization.
For this to work, Commodore needs to have access to an authorized SSH key.

== PyPI

We recommend that you use the Commodore Python package provided on PyPI to make `commodore` available locally.

=== Prerequisites

* Python 3.7, 3.8 or 3.9 as `python3` and the Python `venv` module.
We recommend that you install Python and the `venv` module with your preferred package manager.
* `jsonnet-bundler`, https://github.com/jsonnet-bundler/jsonnet-bundler#install[installation instructions]
* Helm 3, https://helm.sh/docs/intro/install/[installation instructions]

[IMPORTANT]
====
Other documentation assumes that Helm 3 is available as `helm` and `helm3`, and Helm 2 is available as `helm2` in `$PATH`.
Please make sure you setup the Helm binaries accordingly on your local system.
====

[WARNING]
====
As of 2021–11–03, Commodore doesn't yet support Python 3.10+.
====

=== Installation

Generally, it's best to create a separate https://docs.python.org/3.9/tutorial/venv.html[virtualenv] for Python utilities.
Having separate virtualenvs avoids running into dependency conflicts when installing multiple Python utilities from PyPI.

. Check your Python version
+
[source,bash]
----
python3 --version
----
+
This command should report something like
+
[source]
----
Python 3.8.10
----

. Create a virtualenv in `~/.local/commodore-venv`
+
[source,bash]
----
python3 -m venv ~/.local/commodore-venv
----

. Activate the virtualenv
+
[source,bash]
----
source ~/.local/commodore-venv/bin/activate
----

. Install Commodore into the virtualenv
+
[source,bash]
----
pip install syn-commodore
----

. Check that `commodore` was installed correctly
+
[source,bash]
----
commodore --version
----

=== Usage

If you've installed Commodore into a virtualenv, you need to activate the virtualenv whenever you want to run Commodore.

[source,bash]
----
source ~/.local/commodore-venv/bin/activate
----

After that, you can run Commodore with

[source,bash]
----
commodore --help
----

TIP: To leave the virtualenv, you can execute the `deactivate` command.

== Docker

If you want, you can also use the Commodore container image locally.

In that case, the following shell functions can be placed in your shells configuration file (for example `~/.profile`, `~/.bashrc`, `.zshrc` etc.).
By doing so, you can run commodore as if it was any other executable on your system.

=== Linux

On Linux it's possible to use SSH agent and mounting the agents socket into the container.

[source,bash]
----
commodore() {
  docker run \
    --interactive=true \
    --tty \
    --rm \
    --user="$(id -u)" \
    --env COMMODORE_API_URL=$COMMODORE_API_URL \
    --env COMMODORE_API_TOKEN=$COMMODORE_API_TOKEN \
    --env SSH_AUTH_SOCK=/tmp/ssh_agent.sock \
    --volume "${SSH_AUTH_SOCK}:/tmp/ssh_agent.sock" \
    --volume "${HOME}/.ssh/config:/app/.ssh/config:ro" \
    --volume "${HOME}/.ssh/known_hosts:/app/.ssh/known_hosts:ro" \
    --volume "${HOME}/.gitconfig:/app/.gitconfig:ro" \
    --volume "${PWD}:/app/data" \
    --workdir /app/data \
    projectsyn/commodore:${COMMODORE_VERSION:=latest} \
    $*
}
----

=== macOS

On macOS with Docker for Mac mounting the SSH agents socket into a container doesn't work.
Instead you need to mount as magic path that's provided by Docker for Mac.

[NOTE]
====
This only works for the stock ssh-agent coming along with macOS.
If you use any other agent, you might be out of luck.
Docker for mac doesn't support mounting sockets.
====

[CAUTION]
====
That magic socket path belongs to root.
One must run a container with `--user=0` in order to access it.
This doesn't mess up your file permissions thanks to the magic of how volume mount work on Docker for Mac.
====

[source,bash]
----
commodore() {
  docker run \
    --interactive=true \
    --tty \
    --rm \
    --user="0" \
    --env COMMODORE_API_URL=$COMMODORE_API_URL \
    --env COMMODORE_API_TOKEN=$COMMODORE_API_TOKEN \
    --env SSH_AUTH_SOCK=/tmp/ssh_agent.sock \
    --volume "/run/host-services/ssh-auth.sock:/tmp/ssh_agent.sock" \
    --volume "${HOME}/.ssh/config:/app/.ssh/config:ro" \
    --volume "${HOME}/.ssh/known_hosts:/app/.ssh/known_hosts:ro" \
    --volume "${HOME}/.gitconfig:/app/.gitconfig:ro" \
    --volume "${PWD}:/app/data" \
    --workdir /app/data \
    projectsyn/commodore:latest \
    $*
}
----

Instead you can also mount your SSH key into the container.
The container will pickup that key and add it do an SSH agent running inside the container.
You will be prompted to insert your SSH keys password if it has one.

[source,bash]
----
commodore() {
  docker run \
    --interactive=true \
    --tty \
    --rm \
    --user="$(id -u)" \
    --env COMMODORE_API_URL=$COMMODORE_API_URL \
    --env COMMODORE_API_TOKEN=$COMMODORE_API_TOKEN \
    --volume "${HOME}/.ssh:/app/.ssh:ro" \
    --volume "${HOME}/.gitconfig:/app/.gitconfig:ro" \
    --volume "${PWD}:/app/data" \
    --workdir /app/data \
    projectsyn/commodore:latest \
    $*
}
----
[NOTE]
====
If you have multiple SSH keys, you can mount only the one you need for commodore.
This will remove the password prompt for each and every SSH key.
Do this by using the following volumes instead of the line `--volume "${HOME}/.ssh:/app/.ssh:ro" \`

[source,bash]
----
    --volume "${HOME}/.ssh/config:/app/.ssh/config:ro" \
    --volume "${HOME}/.ssh/known_hosts:/app/.ssh/known_hosts:ro" \
    --volume "/path/to/your/key:/app/.ssh/id_rsa:ro" \ <1>
----
<1> Replace `/path/to/your/key` according to your needs.
====
