= Deprecation notices

This page lists deprecations of Commodore features organized by version.
We include a link to relevant documentation, if applicable.

== Unreleased

== https://github.com/projectsyn/commodore/releases/tag/v0.13.0[v0.13.0]

=== `parameters.commodore.jsonnet_libs` is removed

The parameter has been deprecated since Commodore v0.6.0, and is removed in v0.13.0.

== https://github.com/projectsyn/commodore/releases/tag/v0.6.0[v0.6.0]

=== `parameters.commodore.jsonnet_libs` is deprecated

Users should specify Jsonnet dependencies of components in the component's `jsonnetfile.json`.

For now, Commodore itself ensures `kube-libsonnet` is available as `lib/kube.libsonnet`.

== https://github.com/projectsyn/commodore/releases/tag/v0.5.0[v0.5.0]

=== `parameters.component_versions` is deprecated

Users should switch to xref:commodore:ROOT:reference/architecture.adoc#_component_discovery_and_versions[`parameters.components`] which has the exact same format.

== https://github.com/projectsyn/commodore/releases/tag/v0.4.0[v0.4.0]

* Class includes of components are removed.
  Instead components *must* be included with entries in the `applications` array.

== https://github.com/projectsyn/commodore/releases/tag/v0.3.0[v0.3.0]

* The reclass hierarchy must be configured in the global defaults repository.
  See xref:commodore:ROOT:reference/hierarchy.adoc[the reference docs] for details.

* The following parameters will be removed in a future release.
  They're replaced by keys in `parameters.facts` and `parameters.cluster`:
+
** `parameters.cluster.dist` -> `parameters.facts.distribution`
** `parameters.cloud.provider` -> `parameters.facts.cloud`
** `parameters.cloud.region` -> `parameters.facts.region`
** `parameters.customer.name` -> `parameters.cluster.tenant`


== https://github.com/projectsyn/commodore/releases/tag/v0.2.0[v0.2.0]

* Command structure has been reorganized.
  See xref:commodore:ROOT:reference/commands.adoc[the commands documentation].
