= Deprecation notices

This page lists deprecations of Commodore features organized by version.
We include a link to relevant documentation, if applicable.

== https://github.com/projectsyn/commodore/releases/tag/v0.16.0[v0.16.0]

[#_external_pp_filters]
=== External postprocessing filter definitions are deprecated

Commodore v0.4.0 introduced support for defining postprocessing filters in the component class.
However, defining postprocessing filters in `postprocess/filters.yml` was never formally deprecated.

To migrate a component which still uses `postprocess/filters.yml`, you can simply move the contents of the file to parameter `commodore.postprocess`, remove the file and commit the changes.

[source,bash]
----
component_name=component-name
export filters=$(yq e '.' postprocess/filters.yml)
yq e -i '.parameters.commodore.postprocess = env(filters)' "class/${component_name}.yml"
rm -rf postprocess/
git add -u
git commit -m "Move postprocessing filter definitions to component class"
----

TIP: The provided snippet uses https://github.com/mikefarah/yq[mikefarah/yq v4].

[#_component_lib_naming]
=== Component library names which aren't prefixed with the component name are deprecated

Commodore v0.16.0 adds support for explicitly specifying component library aliases.
In turn, the previous approach of allowing components to provide libraries with arbitrary names is deprecated.
Instead components should always prefix their component libraries with the component name.
This introduces namespacing for component libraries by default.

The aliasing mechanism still allows multiple components which implement the same interface to expose their implementation of the shared interface under an arbitrary alias.

NOTE: Commodore will raise an error if multiple components in the hierarchy try to use the same component library alias.

== https://github.com/projectsyn/commodore/releases/tag/v0.14.0[v0.14.0]

[#_multi_instance_top_level]
=== Advertising multi-instance support in component parameter `multi_instance` is deprecated

Commodore v0.14.0 adds support for advertising multi-instance support in components to field `multi_instance` in the component metadata parameter `_metadata`.
In turn the old location for advertising multi-instance support in component parameter `multi_instance` is deprecated.

To update existing components, you can simply adjust the component's `class/defaults.yml` to match the sample shown below.

[source,yaml]
----
parameters:
  <component_name>: <1>
    =_metadata: <2>
      multi_instance: true
----
<1> `<component_name>` is a placeholder for the component's parameters key
<2> By prefixing the `_metadata` key with an equals sign, we make the component metadata constant.
This ensures that values in `_metadata` can't be changed in the hierarchy.
See also the https://github.com/kapicorp/reclass/blob/develop/README-extensions.rst#constant-parameters[Kapitan reclass documentation].

TIP: Depending on the age of the component, the `metadata` key may already exist with empty content.


== https://github.com/projectsyn/commodore/releases/tag/v0.13.0[v0.13.0]

=== `parameters.commodore.jsonnet_libs` is removed

The parameter has been deprecated since Commodore v0.6.0, and is removed in v0.13.0.

[#_components_without_versions]
=== Component specifications without explicit version are deprecated

Users should always specify an explicit `version` in component specifications.
In general, we encourage users to switch to explicitly tagged versions for all components.

TIP: To keep the previous default behavior, users can specify `version: master` in the component specification.

== https://github.com/projectsyn/commodore/releases/tag/v0.6.0[v0.6.0]

=== `parameters.commodore.jsonnet_libs` is deprecated

Users should specify Jsonnet dependencies of components in the component's `jsonnetfile.json`.

For now, Commodore itself ensures `kube-libsonnet` is available as `lib/kube.libsonnet`.

== https://github.com/projectsyn/commodore/releases/tag/v0.5.0[v0.5.0]

=== `parameters.component_versions` is deprecated

Users should switch to xref:commodore:ROOT:reference/architecture.adoc#_component_discovery_and_versions[`parameters.components`] which has the exact same format.

== https://github.com/projectsyn/commodore/releases/tag/v0.4.0[v0.4.0]

* Class includes of components are removed.
  Instead components *must* be included with entries in the `applications` array.

== https://github.com/projectsyn/commodore/releases/tag/v0.3.0[v0.3.0]

* The reclass hierarchy must be configured in the global defaults repository.
  See xref:commodore:ROOT:reference/hierarchy.adoc[the reference docs] for details.

* The following parameters will be removed in a future release.
  They're replaced by keys in `parameters.facts` and `parameters.cluster`:
+
** `parameters.cluster.dist` -> `parameters.facts.distribution`
** `parameters.cloud.provider` -> `parameters.facts.cloud`
** `parameters.cloud.region` -> `parameters.facts.region`
** `parameters.customer.name` -> `parameters.cluster.tenant`


== https://github.com/projectsyn/commodore/releases/tag/v0.2.0[v0.2.0]

* Command structure has been reorganized.
  See xref:commodore:ROOT:reference/commands.adoc[the commands documentation].
