= Local mode

Commodore provides a local mode for the `compile` command. Local mode is
intended for local development, and won't fetch information from the
SYNventory API or clone Git repositories for the inventory and components.


Local mode can be enabled with the `--local` flag of the `compile` command.

[source,bash]
--
poetry run commodore catalog compile <cluster-id> --local
--

In local mode, the existing directory structure in the working directory is
used. This allows local development on components and also allows testing
local modifications to the inventory. The user is responsible for ensuring
that all the moving parts are where they should be. It's recommended to run
Commodore in regular mode once to fetch all the inputs which are required to
compile the catalog for the selected cluster.

[source,bash]
--
poetry run commodore catalog compile <cluster-id>
--

To test a component which is new to a cluster in local mode, the component has to be downloaded and symlinked into the directory structure of a previous `commodore catalog compile`.

[source,bash]
--
COMPONENT_NAME=
COMPONENT_GIT_URL=

git clone ${COMPONENT_GIT_URL} ./dependencies/${COMPONENT_NAME}

ln -svf ../../../dependencies/${COMPONENT_NAME}/class/defaults.yml ./inventory/classes/defaults/${COMPONENT_NAME}.yml
ln -svf ../../../dependencies/${COMPONENT_NAME}/class/${COMPONENT_NAME}.yml ./inventory/classes/components/${COMPONENT_NAME}.yml

ln -svf ../dependencies/${COMPONENT_NAME} ./vendor/${COMPONENT_NAME}
--

To configure the target for the new component the one of argocd can be copied as this is usually present in all clusters.

[source,bash]
--
cp ./inventory/targets/argocd.yml ./inventory/targets/${COMPONENT_NAME}.yml
sed -i "s/ argocd/ ${COMPONENT_NAME}/g" ./inventory/targets/${COMPONENT_NAME}.yml
sed -i "s/- components.argocd/- defaults.${COMPONENT_NAME}\n- components.${COMPONENT_NAME}/g" ./inventory/targets/${COMPONENT_NAME}.yml
--
