FROM golang:1.16-stretch as builder

ARG PY_VER='python3.6'

WORKDIR /virtualenv
COPY ./lib/${PY_VER}/site-packages/kapitan ./kapitan
RUN ./kapitan/inputs/helm/build.sh
RUN ./kapitan/dependency_manager/helm/build.sh
