# Pushed to docker.io/vshn/kapitan:v0.27.2

FROM docker.io/alpine:3.11

ENV KAPITAN_VERSION=v0.27.2

RUN apk add --no-cache \
        ca-certificates \
        curl \
 && curl -Lo /usr/local/bin/kapitan https://github.com/deepmind/kapitan/releases/download/${KAPITAN_VERSION}/kapitan-linux-amd64 \
 && chmod +x /usr/local/bin/kapitan

USER 10001
