FROM docker.io/ubuntu:focal
MAINTAINER VSHN AG <tech@vshn.ch>

ENV DEBIAN_FRONTEND=noninteractive

RUN set -ex \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
   ca-certificates \
   curl \
   make \
   yamllint \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV JSONNET_VERSION=v0.16.0 \
    JSONNET_ARCHIVE=/tmp/jsonnet.tar.gz

RUN set -ex \
 && curl -sfLo ${JSONNET_ARCHIVE} https://github.com/google/jsonnet/releases/download/${JSONNET_VERSION}/jsonnet-bin-${JSONNET_VERSION}-linux.tar.gz \
 && tar xvfz ${JSONNET_ARCHIVE} -C /usr/local/bin \
 && rm ${JSONNET_ARCHIVE}
