#!/bin/bash
# run a ssh as (non-existent) user, using libnss-wrapper

U=$(id -u)
G=$(id -g)

HOME_DIR=/tmp/user
PASSWD=/var/tmp/passwd
GROUP=/var/tmp/group

if [ ! -d "$HOME_DIR" ]; then
    mkdir "$HOME_DIR"
fi
if [ ! -f "$PASSWD" ]; then
    echo "user::$U:$G::$HOME_DIR:" > "$PASSWD"
fi
if [ ! -f "$GROUP" ]; then
    echo "user::$G:" > "$GROUP"
fi

echo "${SSH_PRIVATE_KEY}" > /app/.identityfile
chmod 600 /app/.identityfile

LD_PRELOAD=libnss_wrapper.so \
NSS_WRAPPER_PASSWD="$PASSWD" \
NSS_WRAPPER_GROUP="$GROUP" \
ssh -i /app/.identityfile \
    -oGlobalKnownHostsfile=/app/.known_hosts \
    "$@"

# vim: set et sw=4 ts=4 :
